### ISSUE TITLE
Do you have plans on making the Citizen Archivist Dashboard code public?

### ISSUE THREAD

**Issue by lukefretwell** [usnationalarchives/feedback#3]

**Comment by mereastew** [comment]
Hi @Lukefretwell, thanks for the question. Right now the Citizen Archivist Dashboard (http://www.archives.gov/citizen-archivist/) is a group of HTML webpages that function as a portal for our crowdsourcing initiatives. The Dashboard is an aggregate of listings and links. Some of these projects are open source projects, including our Transcription Pilot Project (http://transcribe.archives.gov/). We have released the distribution for that application on Drupal (https://drupal.org/project/transcribe_distribution). As we make updates to the Citizen Archivist Dashboard and projects in the future, any code that can be made available will be released. We are currently working on improvements to our online catalog (http://www.archives.gov/research/search/) for release later this year that will introduce new crowdsourcing fields and “write” API functions for those fields. You can learn more about these efforts in NARA’s Open Government Plan for 2014-2016 at http://www.archives.gov/open/open-government-plan-3.0.pdf (starting on page 16). We hope the availability of a public API for the catalog will spur new crowdsourcing projects and innovations.
